apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: static-web
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /api/info {
            default_type application/json;
            return 200 '{"podName":"static-web","nodeName":"k8s-node"}';
        }
    }
