apiVersion: apps/v1
kind: Deployment
metadata:
  name: static_web_site_k8s-deployment
  labels:
    app: static_web_site_k8s
spec:
  replicas: 1  # Un seul pod sur node1
  selector:
    matchLabels:
      app: static_web_site_k8s
  template:
    metadata:
      labels:
        app: static_web_site_k8s
    spec:
      nodeName: node1  # Forcer l'exécution sur node1
      containers:
      - name: static_web_site_k8s
        image: VOTRE_USERNAME_DOCKER/static_web_site_k8s-app:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"